/**
 * Main types export file for Project Yarn
 * Provides centralized access to all TypeScript types and utilities
 */

// Component types
export type {
  BaseComponentProps,
  PolymorphicProps,
  PolymorphicComponent,
  VariantProps,
  SizeVariant,
  ColorVariant,
  ComponentState,
  EventHandler,
  ClickHandler,
  ChangeHandler,
  FocusHandler,
  KeyboardHandler,
  FormHandler,
  FormFieldProps,
  FormFieldState,
  FormFieldValidator,
  LoadingState,
  AsyncState,
  PaginationState,
  PaginatedData,
  SortDirection,
  SortState,
  FilterState,
  WithChildren,
  WithOptionalChildren,
  WithRequiredChildren,
  RenderProp,
  RenderPropComponent,
  ForwardedRefComponent,
  ComponentFactory,
  ThemeAwareProps,
  ResponsiveValue,
  AnimationProps,
  TransitionProps,
  AccessibilityProps,
  PerformanceMetrics,
  ComponentPerformanceData,
  VirtualizationProps,
  VirtualItem,
  ComponentMetadata,
  ErrorInfo,
  ErrorBoundaryState,
  ContextValue,
  ContextProviderProps,
  UseToggleReturn,
  UseCounterReturn,
  UseLocalStorageReturn,
  Prettify,
  Optional,
  Required,
  DeepPartial,
  DeepRequired,
  PropsOf,
  CreateVariant,
  TypedEventEmitter,
  ComponentRegistry,
  RegisteredComponent
} from './component-types';

// Hook types
export type {
  HookOptions,
  AsyncHookState,
  AsyncHookActions,
  AsyncHookReturn,
  FetchOptions,
  UseFetchOptions,
  UseFetchReturn,
  UseLocalStorageOptions,
  UseLocalStorageReturn,
  FormFieldConfig,
  FormConfig,
  FormFieldState,
  FormState,
  FormActions,
  UseFormReturn,
  UseMediaQueryOptions,
  UseMediaQueryReturn,
  UseIntersectionObserverOptions,
  UseIntersectionObserverReturn,
  UseResizeObserverOptions,
  UseResizeObserverReturn,
  EventMap,
  UseEventListenerOptions,
  UseDebounceOptions,
  UseThrottleOptions,
  DebouncedFunction,
  UseAnimationOptions,
  UseAnimationReturn,
  UseDragOptions,
  UseDropOptions,
  UseDragReturn,
  UseDropReturn,
  UseKeyboardOptions,
  KeyboardEventHandler,
  UseFocusTrapOptions,
  UseFocusTrapReturn,
  UseClipboardOptions,
  UseClipboardReturn,
  UseGeolocationOptions,
  UseGeolocationReturn,
  BatteryManager,
  UseBatteryReturn,
  UseNetworkReturn,
  UsePermissionOptions,
  UsePermissionReturn,
  UseWebSocketOptions,
  UseWebSocketReturn,
  UsePerformanceOptions,
  UsePerformanceReturn,
  UseAriaAnnouncerOptions,
  UseAriaAnnouncerReturn,
  HookFactory,
  HookState,
  HookStateAction,
  ComposedHook,
  HookMiddleware,
  HookWithMiddleware
} from './hook-types';

// Re-export commonly used React types
export type {
  ComponentProps,
  ElementType,
  ReactNode,
  ReactElement,
  RefObject,
  MutableRefObject,
  DependencyList,
  EffectCallback,
  Dispatch,
  SetStateAction,
  Reducer,
  ReducerState,
  ReducerAction
} from 'react';

// Type utilities
export { typeUtils as default } from '../lib/type-utils';
export {
  typeGuards,
  assertions,
  propUtils,
  objectUtils,
  arrayUtils,
  functionUtils,
  promiseUtils,
  validationUtils,
  performanceUtils
} from '../lib/type-utils';

// Type guards (re-exported for convenience)
export {
  isReactElement,
  isFunction,
  isString,
  isNumber,
  isBoolean,
  isObject,
  isArray
} from './component-types';
